import Navbar from "@/components/navbar";
import "./globals.css";
import Footer from "@/components/footer";
import Cart from "@/components/pages/cart/page";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <Cart/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
